import os
from datetime import datetime

DEFAULT_STRUCTURE = """# STRUCTURE.md — Project Documentation

This file is automatically maintained by **Auto-Doc Janitor**. It provides a high-level overview of the components in this directory.

## 📁 Directory Overview

---
*Generated by [Auto-Doc Janitor](https://github.com/s655liu/DocJanitor)*
"""

def patch_docs(file_path, summary_info):
    """
    Writes the AI-generated STRUCTURE.md update.
    Creates STRUCTURE.md if it doesn't exist.
    """
    structure_path = summary_info.get('structure_path', '')
    
    if not structure_path:
        # Look for STRUCTURE.md in the same directory as the changed file
        structure_path = os.path.join(os.path.dirname(file_path), "STRUCTURE.md")
    
    # Create STRUCTURE.md if it doesn't exist
    if not os.path.exists(structure_path):
        dir_path = os.path.dirname(structure_path)
        if dir_path and not os.path.exists(dir_path):
            os.makedirs(dir_path)
        with open(structure_path, "w", encoding="utf-8") as f:
            f.write(DEFAULT_STRUCTURE)
        print(f"[Doc Patcher] Created new: {structure_path}")
    
    # Write the updated content
    if summary_info.get('patch'):
        with open(structure_path, "w", encoding="utf-8") as f:
            f.write(summary_info['patch'])
        print(f"[Doc Patcher] Updated: {structure_path}")
    else:
        print(f"[Doc Patcher] No patch to apply.")
